task: ISLR
data:
  input_data: videos  # Utilizza solo video
  input_streams:
    - rgb  # Rimosso 'keypoint', perché non hai dati di keypoints
  #zip_file: ../../data/isolatedLIS/videos.zip   Se lavori con un archivio
  train: /kaggle/working/CV-Project/SLRT-main/TwoStreamNetwork/data/isolatedLIS/annotations/train.train
  dev: /kaggle/working/CV-Project/SLRT-main/TwoStreamNetwork/data/isolatedLIS/annotations/val.dev
  test: /kaggle/working/CV-Project/SLRT-main/TwoStreamNetwork/data/isolatedLIS/annotations/test.test
  vocab_file: /kaggle/working/CV-Project/SLRT-main/TwoStreamNetwork/data/isolatedLIS/annotations/vocab.vocab
  dataset_name: isolatedLIS
  level: word
  txt_lowercase: true
  num_output_frames: 16
  max_sent_length: 400
  transform_cfg:
    img_size: 224
    color_jitter: true
    center_crop_size: 270
    center_crop: true
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3

testing:
  cfg:
    recognition:
      beam_size: 1

training:
  overwrite: True
  model_dir: results/isolatedLIS_ISLR
  random_seed: 321
  shuffle: True
  num_workers: 8
  batch_size: 4  # Puoi aumentarlo se hai più memoria
  total_epoch: 100
  keep_last_ckpts: 1
  validation: 
    unit: epoch
    freq: 1
    cfg:
      recognition:
        beam_size: 1
  optimization:
    optimizer: Adam
    learning_rate:
      default: 6.0e-4
    weight_decay: 0.001
    betas:
      - 0.9
      - 0.998
    scheduler: cosineannealing
    t_max: 100

model:
  RecognitionNetwork:
    GlossTokenizer:
      gloss2id_file: ../../pretrained_models/mBart_de_2/gloss2ids.pkl
    s3d:
      pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt  # Usa solo RGB
      use_block: 5
      freeze_block: 0
    keypoint_s3d: null  # Disattivato perché non hai keypoints
    fuse_method: rgb_only  # Usa solo il flusso video
    lateral:
      pose2rgb: false  # Disattivato perché non hai pose
      rgb2pose: false
    aux_head:
      head_weight_rgb: 0.2
      head_weight_keypoint: 0.0  # Disattivato
      num: 0
    visual_head:
      variant: sep_conv
      use_extra_linear: false
      input_size: 1024
      hidden_size: 512
      ff_size: 2048
      pe: true
      word_emb_dim: 300
      temp: 0.1
      topk: 1115
      split_setting: split_nonblk
    label_smooth: 0.2
    bag_loss:
      - avg_prob
      - avg_prob
