task: ISLR
data:
  input_data: videos
  input_streams:
    - rgb
  zip_file: /ext/LISDataset/IsolatedLIS.zip
  train: IsolatedLIS/pkl/train.pkl
  dev: IsolatedLIS/pkl/val.pkl
  test: IsolatedLIS/pkl/test.pkl
  vocab_file: IsolatedLIS/pkl/vocab.json
  dataset_name: IsolatedLIS
  level: word
  txt_lowercase: true
  num_output_frames: 16
  max_sent_length: 400
  transform_cfg:
    img_size: 224         # Resize finale
    color_jitter: true
    center_crop: false    # Disattivato
    custom_crop_width: 700
    custom_crop_height: 550
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
  isContinuous: false

testing:
  cfg:
    recognition:
      beam_size: 1

training:
  overwrite: True
  model_dir: /ext/home/scavalent/results/Isolated_training_1 ##prova, poi togliere _1
  random_seed: 321
  shuffle: True
  num_workers: 8
  batch_size: 4
  total_epoch: 100
  keep_last_ckpts: 1
  validation:
    unit: epoch
    freq: 1
    cfg:
      recognition:
        beam_size: 1
  optimization:
    optimizer: Adam
    learning_rate:
      default: 6.0e-4
    weight_decay: 0.001
    betas:
      - 0.9
      - 0.998
    scheduler: cosineannealing
    t_max: 100

model:
  RecognitionNetwork:
    GlossTokenizer:
      gloss2id_file: /ext/LISDataset/pretrained_models/mBart_de_2/mBart_de_2/gloss2ids.pkl
    s3d:
      pretrained_ckpt: /ext/home/scavalent/CV-Project/SLRT-main/Online/CSLR/pretrained_models/S3D_kinetics400.pt
      use_block: 5
      freeze_block: 0
    keypoint_s3d:
      in_channel: 0
      pretrained_ckpt: /ext/home/scavalent/CV-Project/SLRT-main/Online/CSLR/pretrained_models/S3D_kinetics400.pt
      use_block: 5
      freeze_block: 0
    fuse_method: null
    lateral:
      pose2rgb: false
      rgb2pose: false
    aux_head:
      head_weight_rgb: 0.2
      head_weight_keypoint: 0.0
      num: 0
    visual_head:
      variant: sep_conv
      use_extra_linear: false
      input_size: 1024
      hidden_size: 512
      ff_size: 2048
      pe: true
      word_emb_dim: 300
      temp: 0.1
      contras_setting: null
      topk: 1115
      split_setting: split_nonblk
    label_smooth: 0.2
    bag_loss:
      - avg_prob
      - avg_prob
