task: ISLR

data:
  input_data: videos
  input_streams:
    - rgb
  zip_file: /ext/home/scavalent/ContinuousLis.zip #/ext/LISDataset/ContinuousLis.zip
  train: /ext/home/scavalent/data_prova/train.pkl
  dev: /ext/home/scavalent/data_prova/val.pkl
  test: /ext/home/scavalent/data_prova/test.pkl
  vocab_file: /ext/home/scavalent/continuous_vocab/continuous_vocab.json
  dataset_name: IsolatedLIS
  level: word
  txt_lowercase: true
  num_output_frames: 64  # più lungo per video continui
  max_sent_length: 400
  transform_cfg:
    img_size: 224
    color_jitter: true
    center_crop_size: 270
    center_crop: true
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
  isContinuous: true

testing:
  cfg:
    recognition:
      beam_size: 5  # aumentato per output sequenziale

training:
  overwrite: True
  model_dir: /ext/home/scavalent/results/continuous_lis
  pretrained_path: /ext/home/scavalent/results/prova/ckpts/best_copia.pt # modello ISLR
  random_seed: 321
  shuffle: True
  num_workers: 8
  batch_size: 2  # video lunghi = batch più piccolo
  total_epoch: 30
  keep_last_ckpts: 1
  validation: 
    unit: epoch
    freq: 1
    cfg:
      recognition:
        beam_size: 5
  optimization:
    optimizer: Adam
    learning_rate:
      default: 3.0e-4
    weight_decay: 0.001
    betas:
      - 0.9
      - 0.998
    scheduler: cosineannealing
    t_max: 100

model:
  RecognitionNetwork:
    GlossTokenizer:
      gloss2id_file: /ext/home/scavalent/pretrained_models/mBart_de_2/mBart_de_2/gloss2ids.pkl
    s3d:
      pretrained_ckpt: /ext/home/scavalent/results/prova/ckpts/best_copia.pt  # riusa feature extractor
      use_block: 5
      freeze_block: 0
    keypoint_s3d:
      in_channel: 0
      pretrained_ckpt: SLRT-main/Online/CSLR/pretrained_models/S3D_kinetics400.pt
      use_block: 5
      freeze_block: 0
    fuse_method: null
    lateral:
      pose2rgb: false
      rgb2pose: false
    aux_head:
      head_weight_rgb: 0.2
      head_weight_keypoint: 0.0
      num: 0
    visual_head:
      variant: sep_conv
      use_extra_linear: false
      input_size: 1024
      hidden_size: 512
      ff_size: 2048
      pe: true
      word_emb_dim: 300
      temp: 0.1
      contras_setting: null
      topk: 1115
      split_setting: split_nonblk
    label_smooth: 0.2
    bag_loss:
      - avg_prob
      - avg_prob
